/*
 * AI Mastering API
 *
 * This is a AI Mastering API document. You can use the mastering feature of [AI Mastering](https://aimastering.com) through this API.
 *
 * API version: 1.0.0
 * Contact: info@bakuage.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package aimastering

type GroupBuyStatistics struct {

	PremiumPlanSubscribedUserCount int32 `json:"premium_plan_subscribed_user_count,omitempty"`
}
