/*
 * AI Mastering API
 *
 * This is a AI Mastering API document. You can use the mastering feature of [AI Mastering](https://aimastering.com) through this API.
 *
 * API version: 1.0.0
 * Contact: info@bakuage.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package aimastering

type Plan struct {

	Amount int32 `json:"amount,omitempty"`

	Currency string `json:"currency,omitempty"`

	Interval string `json:"interval,omitempty"`

	Name string `json:"name,omitempty"`

	StripePlanId string `json:"stripe_plan_id,omitempty"`
}
